version: "3.9"
services:
  keycloak-postgres:
    image: library/postgres:${POSTGRES_VERSION:-14.5}
    container_name: ${KEYCLOACK_POSTGRES_NAME:-keycloak-postgres}
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${KC_POSTGRES_EXTERNAL_PORT:-5432}:5432
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOACK_VERSION:-20.0.2}
    container_name: ${KEYCLOACK_CONTAINER_NAME:-keycloack-default}
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --import-realm --proxy edge --http-enabled true --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./resources/keycloack/import/agro-realm-import.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - ${KEYCLOACK_EXTERNAL_PORT:-8282}:8080
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
